In [1]:
from sklearn.model_selection import train_test_split
from sklearn.decomposition import PCA
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn import tree
import pickle
import numpy as np

In [2]:
# Load tokenized news data

with open('aapl_two_gram_features_labelled_df.pkl', 'rb') as f:
    labelled_aapl_news_df = pickle.load(f)

In [13]:
trainX_df=labelled_aapl_news_df['features']
trainY_df=labelled_aapl_news_df['label']

trainX = np.stack(trainX_df)

trainY_df=trainY_df.astype('int')
trainY = np.stack(trainY_df)

print(trainX.shape)
print(trainY.shape)
trainX

(71941, 3831)
(71941,)


array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [20]:
pca = PCA(n_components=3800)
pComponents= pca.fit_transform(trainX)
X_train, X_test, y_train, y_test = train_test_split(trainX, trainY, test_size=0.2, random_state=23)

In [21]:
print(X_train.shape)
print(y_train.shape)

(57552, 3831)
(57552,)


In [22]:
clf = LogisticRegression(max_iter=1000)
clf.fit(X_train,y_train)
y_pred=clf.predict(X_test)


In [25]:
print(pca.explained_variance_ratio_)
acc=accuracy_score(y_test,y_pred)
print('Accuracy of LogisticRegression classifier is: %f ' % acc)
print(pca.explained_variance_ratio_.shape)
print(y_pred)
print(y_test)

[8.01939841e-02 4.59203231e-02 3.82233813e-02 ... 7.04995361e-34
 7.04995361e-34 7.04995361e-34]
Accuracy of LogisticRegression classifier is: 0.598652 
(3800,)
[-1 -1 -1 ... -1  1  1]
[-1  1  1 ...  1  1 -1]


In [26]:
#list_temp = "0.08019398 0.04592032 0.03822338 0.02302324 0.01630195 0.01025567 0.00907625 0.00836143 0.00744537 0.00688097 0.00629208 0.00582154 0.00525373 0.00488324 0.00478933".split()
sum([float(x) for x in pca.explained_variance_ratio_])

1.0000000000000004