In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.decomposition import PCA
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn import svm
from sklearn import tree
from tensorflow import keras
import pickle
import datetime
import numpy as np
import pandas as pd

In [ ]:
!wget https://developer.nvidia.com/compute/cuda/9.0/Prod/local_installers/cuda-repo-ubuntu1704-9-0-local_9.0.176-1_amd64-deb

--2021-04-08 05:44:44--  https://developer.nvidia.com/compute/cuda/9.0/Prod/local_installers/cuda-repo-ubuntu1704-9-0-local_9.0.176-1_amd64-deb
Resolving developer.nvidia.com (developer.nvidia.com)... 152.199.0.24
Connecting to developer.nvidia.com (developer.nvidia.com)|152.199.0.24|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://developer.nvidia.com/compute/cuda/9.0/prod/local_installers/cuda-repo-ubuntu1704-9-0-local_9.0.176-1_amd64-deb [following]
--2021-04-08 05:44:45--  https://developer.nvidia.com/compute/cuda/9.0/prod/local_installers/cuda-repo-ubuntu1704-9-0-local_9.0.176-1_amd64-deb
Reusing existing connection to developer.nvidia.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://developer.download.nvidia.com/compute/cuda/9.0/secure/Prod/local_installers/cuda-repo-ubuntu1704-9-0-local_9.0.176-1_amd64.deb?gXoVLQgL8HlJG8L3naHI-iuh6uTszayX9hkWD2vAXPWiTOm4kPrLTLffZ2VTQbwB1BZcA2namDCqe4q50o7gjvuWtprkAGqbB

In [ ]:
!dpkg -i cuda-repo-ubuntu1704-9-0-local_9.0.176-1_amd64-deb

Selecting previously unselected package cuda-repo-ubuntu1704-9-0-local.
(Reading database ... 160980 files and directories currently installed.)
Preparing to unpack cuda-repo-ubuntu1704-9-0-local_9.0.176-1_amd64-deb ...
Unpacking cuda-repo-ubuntu1704-9-0-local (9.0.176-1) ...
Setting up cuda-repo-ubuntu1704-9-0-local (9.0.176-1) ...


In [ ]:
!ls /var/cuda-repo-9-0-local | grep .pub

7fa2af80.pub


In [ ]:
!apt-key add /var/cuda-repo-9-0-local/7fa2af80.pub

OK


In [ ]:
!apt-get update

Get:1 file:/var/cuda-repo-9-0-local  InRelease
Ign:1 file:/var/cuda-repo-9-0-local  InRelease
Get:2 file:/var/cuda-repo-9-0-local  Release [574 B]
Get:2 file:/var/cuda-repo-9-0-local  Release [574 B]
Get:3 file:/var/cuda-repo-9-0-local  Release.gpg [819 B]
Get:3 file:/var/cuda-repo-9-0-local  Release.gpg [819 B]
Ign:4 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease
Get:5 https://cloud.r-project.org/bin/linux/ubuntu bionic-cran40/ InRelease [3,626 B]
Hit:6 http://archive.ubuntu.com/ubuntu bionic InRelease
Get:7 http://ppa.launchpad.net/c2d4u.team/c2d4u4.0+/ubuntu bionic InRelease [15.9 kB]
Ign:8 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  InRelease
Get:9 file:/var/cuda-repo-9-0-local  Packages [15.8 kB]
Hit:10 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  Release
Hit:11 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  Release
Get:12 http:

In [ ]:
!sudo apt-get install cuda-9.0

Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'cuda-9-0' for regex 'cuda-9.0'
Note, selecting 'libcuda-9.0-1' for regex 'cuda-9.0'
The following additional packages will be installed:
  cuda-command-line-tools-9-0 cuda-core-9-0 cuda-cublas-9-0
  cuda-cublas-dev-9-0 cuda-cudart-9-0 cuda-cudart-dev-9-0 cuda-cufft-9-0
  cuda-cufft-dev-9-0 cuda-curand-9-0 cuda-curand-dev-9-0 cuda-cusolver-9-0
  cuda-cusolver-dev-9-0 cuda-cusparse-9-0 cuda-cusparse-dev-9-0
  cuda-demo-suite-9-0 cuda-documentation-9-0 cuda-driver-dev-9-0
  cuda-libraries-9-0 cuda-libraries-dev-9-0 cuda-license-9-0
  cuda-misc-headers-9-0 cuda-npp-9-0 cuda-npp-dev-9-0 cuda-nvgraph-9-0
  cuda-nvgraph-dev-9-0 cuda-nvml-dev-9-0 cuda-nvrtc-9-0 cuda-nvrtc-dev-9-0
  cuda-runtime-9-0 cuda-samples-9-0 cuda-toolkit-9-0 cuda-visual-tools-9-0
The following NEW packages will be installed:
  cuda-9-0 cuda-command-line-tools-9-0 cuda-core-9-0 cuda-cublas-9-0
  cuda-cublas-de

In [ ]:
!nvcc --version

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Sep__1_21:08:03_CDT_2017
Cuda compilation tools, release 9.0, V9.0.176


In [ ]:
!pip install thundersvm

     |████████████████████████████████| 512kB 4.3MB/s 


In [ ]:
from thundersvm import SVC

In [ ]:
from sklearn.model_selection import KFold

In [ ]:
with open('/content/drive/MyDrive/CSE573-SWM-Data/features_bert.pkl', 'rb') as f:
    labelled_aapl_news_df = pickle.load(f)

In [ ]:
with open('/content/drive/MyDrive/CSE573-SWM-Data/AaplLabelledNewsData-OrderPreserved.pkl', 'rb') as f:
    label = pickle.load(f)

In [ ]:
with open('/content/drive/MyDrive/CSE573-SWM-Data/AmznLabelledNewsData-OrderPreserved.pkl', 'rb') as f:
    labelled_amzn_news_df = pickle.load(f)

In [ ]:
with open('/content/drive/MyDrive/CSE573-SWM-Data/BERT_features/features_amzn_bert.pkl', 'rb') as f:
    features_amzn = pickle.load(f)

In [ ]:
trainY_df=label['label']

In [ ]:
trainY_df=trainY_df.astype('int')
trainY = np.stack(trainY_df)

In [ ]:
trainY

array([-1,  1,  1, ...,  1,  1,  1])

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(labelled_aapl_news_df,trainY,test_size=0.1,random_state=0)

In [ ]:
print(X_train.shape)
print(y_train.shape)

(64746, 768)
(64746,)


In [ ]:
#Single run
model = SVC(C=100, kernel='rbf')
print("training SVM now ...")
# Fit the model to training data
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

# Check test set accuracy
accuracy = model.score(X_test, y_test)

print('Accuracy: {}'.format(accuracy))

training SVM now ...
Accuracy: 0.6001389854065323


In [ ]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [ ]:
matrix = confusion_matrix(y_test, y_pred, labels=[1,-1])
print('Confusion Matrix: \n',matrix)

tp, fn, fp, tn = confusion_matrix(y_test, y_pred, labels = [1, -1]).reshape(-1)
print('Outcome values: \n', tp, fn, fp, tn)

matrix = classification_report(y_test, y_pred, labels=[1,-1])
print('Classification report: \n',matrix)


ValueError: ignored

In [ ]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_val_predict

In [ ]:
X = X_train
y = y_train

k = 10
kf = KFold(n_splits=k, random_state=None)

svc = SVC(C=100, kernel='rbf')

result = cross_val_score(svc, X, y, cv = kf)


In [ ]:
result

array([0.5953668 , 0.59073359, 0.59320463, 0.61220077, 0.59953668,
       0.60741313, 0.59530429, 0.60009268, 0.59901143, 0.58449181])

In [ ]:
result.mean()  
#AAple Data

0.5977355814705212

In [ ]:
trainy_df = labelled_amzn_news_df['label']

In [ ]:
trainy_df=trainy_df.astype('int')
trainy = np.stack(trainy_df)

In [ ]:
trainy.shape

(19916,)

In [ ]:
#Amazon Data

X_train,X_test,y_train,y_test=train_test_split(features_amzn,trainy,test_size=0.1,random_state=0)

In [ ]:
X = X_train
y = y_train

k = 10
kf = KFold(n_splits=k, random_state=None)

svc = SVC(C=100, kernel='rbf')

result = cross_val_score(svc, X, y, cv = kf)

In [ ]:
result

array([0.6196319 , 0.59955382, 0.61851645, 0.62353597, 0.61886161,
       0.60993304, 0.59654018, 0.60714286, 0.60993304, 0.609375  ])