# All the libraries used in this notebook

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.decomposition import PCA
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn import svm
from sklearn import tree
from tensorflow import keras
import pickle
import datetime
import numpy as np
from sklearn.feature_selection import chi2
from sklearn.feature_selection import SelectKBest

#Loading the Apple two gram features for 4 hour time interval

In [ ]:
with open('/content/drive/MyDrive/SWM/CSE573-SWM-Data/aapl_two_gram_4_hours_features_labelled_df.pkl', 'rb') as f:
    labelled_aapl_news_df = pickle.load(f)

#Splitting the dataset for training and testing

In [ ]:
trainX_df=labelled_aapl_news_df['features']
trainY_df=labelled_aapl_news_df['label']
trainX = np.stack(trainX_df)

trainY_df=trainY_df.astype('int')
trainY = np.stack(trainY_df)

In [ ]:
print(trainX.shape)
print(trainY.shape)

(72122, 819)
(72122,)


#Feature Extraction using chi2

In [ ]:
chi2_selector = SelectKBest(chi2, k = 500)
chi_trainX = chi2_selector.fit_transform(trainX, trainY)
X_train, X_test, y_train, y_test = train_test_split(chi_trainX, trainY, test_size=0.2, random_state=23)
print(X_train.shape)
print(y_train.shape)

(57697, 500)
(57697,)


#Logistic Regression

*   Accuracy: 54.6%



In [ ]:
print("training Logistic Regression now ...")

logistic_regression = LogisticRegression(max_iter=1000, verbose=15).fit(X_train,y_train)
y_pred = logistic_regression.predict(X_test)
acc = accuracy_score(y_test,y_pred)

print('Accuracy of Logistic Regression classifier is: %f ' % acc)

training Logistic Regression now ...


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


Accuracy of Logistic Regression classifier is: 0.546205 


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    6.4s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    6.4s finished


In [ ]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
matrix = confusion_matrix(y_test,y_pred, labels=[1,-1])
print('Confusion matrix : \n',matrix)

# outcome values order in sklearn
tp, fn, fp, tn = confusion_matrix(y_test,y_pred,labels=[1,-1]).reshape(-1)
print('Outcome values : \n', tp, fn, fp, tn)

# classification report for precision, recall f1-score and accuracy
matrix = classification_report(y_test,y_pred,labels=[1,-1])
print('Classification report : \n',matrix)

Confusion matrix : 
 [[5437 1948]
 [4598 2442]]
Outcome values : 
 5437 1948 4598 2442
Classification report : 
               precision    recall  f1-score   support

           1       0.54      0.74      0.62      7385
          -1       0.56      0.35      0.43      7040

    accuracy                           0.55     14425
   macro avg       0.55      0.54      0.53     14425
weighted avg       0.55      0.55      0.53     14425



#Decision Tree

*   Accuracy: 57.4%



In [ ]:
print("training Decision Tree now ...")
decision_tree = tree.DecisionTreeClassifier(random_state=0).fit(X_train,y_train)
y_pred = decision_tree.predict(X_test)
acc=accuracy_score(y_test,y_pred)
print('Accuracy of Decision Tree classifier is: %f ' % acc)

training Decision Tree now ...
Accuracy of Decision Tree classifier is: 0.574003 


In [ ]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
matrix = confusion_matrix(y_test,y_pred, labels=[1,-1])
print('Confusion matrix : \n',matrix)

# outcome values order in sklearn
tp, fn, fp, tn = confusion_matrix(y_test,y_pred,labels=[1,-1]).reshape(-1)
print('Outcome values : \n', tp, fn, fp, tn)

# classification report for precision, recall f1-score and accuracy
matrix = classification_report(y_test,y_pred,labels=[1,-1])
print('Classification report : \n',matrix)

Confusion matrix : 
 [[5531 1854]
 [4291 2749]]
Outcome values : 
 5531 1854 4291 2749
Classification report : 
               precision    recall  f1-score   support

           1       0.56      0.75      0.64      7385
          -1       0.60      0.39      0.47      7040

    accuracy                           0.57     14425
   macro avg       0.58      0.57      0.56     14425
weighted avg       0.58      0.57      0.56     14425



#Random Forest Classifier

*   Accuracy: 59.8%



In [ ]:
print("training Random Forest classifier now ...")

random_forest_classifier = RandomForestClassifier(n_estimators=100, verbose=15, n_jobs=-1).fit(X_train,y_train)
#increase n_estimators if you face issues in training
y_pred=random_forest_classifier.predict(X_test)
acc=accuracy_score(y_test,y_pred)
print('Accuracy of Random Forest classifier is: %f ' % acc)

training Random Forest classifier now ...
building tree 1 of 100
building tree 2 of 100


[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done   1 tasks      | elapsed:    3.0s


building tree 3 of 100


[Parallel(n_jobs=-1)]: Done   2 tasks      | elapsed:    3.2s


building tree 4 of 100


[Parallel(n_jobs=-1)]: Done   3 tasks      | elapsed:    6.1s


building tree 5 of 100


[Parallel(n_jobs=-1)]: Done   4 tasks      | elapsed:    6.4s


building tree 6 of 100
building tree 7 of 100


[Parallel(n_jobs=-1)]: Done   5 tasks      | elapsed:    9.3s


building tree 8 of 100


[Parallel(n_jobs=-1)]: Done   6 tasks      | elapsed:    9.6s
[Parallel(n_jobs=-1)]: Done   7 tasks      | elapsed:   12.3s


building tree 9 of 100


[Parallel(n_jobs=-1)]: Done   8 tasks      | elapsed:   12.7s


building tree 10 of 100


[Parallel(n_jobs=-1)]: Done   9 tasks      | elapsed:   15.4s


building tree 11 of 100


[Parallel(n_jobs=-1)]: Done  10 tasks      | elapsed:   15.7s


building tree 12 of 100


[Parallel(n_jobs=-1)]: Done  11 tasks      | elapsed:   18.6s


building tree 13 of 100


[Parallel(n_jobs=-1)]: Done  12 tasks      | elapsed:   18.8s


building tree 14 of 100


[Parallel(n_jobs=-1)]: Done  13 tasks      | elapsed:   21.8s
[Parallel(n_jobs=-1)]: Done  14 tasks      | elapsed:   21.9s


building tree 15 of 100
building tree 16 of 100


[Parallel(n_jobs=-1)]: Done  15 tasks      | elapsed:   24.9s
[Parallel(n_jobs=-1)]: Done  16 tasks      | elapsed:   25.0s


building tree 17 of 100
building tree 18 of 100


[Parallel(n_jobs=-1)]: Done  17 tasks      | elapsed:   28.0s
[Parallel(n_jobs=-1)]: Done  18 tasks      | elapsed:   28.1s


building tree 19 of 100
building tree 20 of 100


[Parallel(n_jobs=-1)]: Done  19 tasks      | elapsed:   31.1s
[Parallel(n_jobs=-1)]: Done  20 tasks      | elapsed:   31.2s


building tree 21 of 100
building tree 22 of 100


[Parallel(n_jobs=-1)]: Done  21 tasks      | elapsed:   34.2s


building tree 23 of 100


[Parallel(n_jobs=-1)]: Done  22 tasks      | elapsed:   34.5s


building tree 24 of 100


[Parallel(n_jobs=-1)]: Done  23 tasks      | elapsed:   37.3s


building tree 25 of 100


[Parallel(n_jobs=-1)]: Done  24 tasks      | elapsed:   37.5s


building tree 26 of 100
building tree 27 of 100


[Parallel(n_jobs=-1)]: Done  25 tasks      | elapsed:   40.4s
[Parallel(n_jobs=-1)]: Done  26 tasks      | elapsed:   40.7s


building tree 28 of 100


[Parallel(n_jobs=-1)]: Done  27 tasks      | elapsed:   43.6s


building tree 29 of 100


[Parallel(n_jobs=-1)]: Done  28 tasks      | elapsed:   43.9s


building tree 30 of 100


[Parallel(n_jobs=-1)]: Done  29 tasks      | elapsed:   46.7s


building tree 31 of 100


[Parallel(n_jobs=-1)]: Done  30 tasks      | elapsed:   47.0s


building tree 32 of 100


[Parallel(n_jobs=-1)]: Done  31 tasks      | elapsed:   49.8s
[Parallel(n_jobs=-1)]: Done  32 tasks      | elapsed:   50.0s


building tree 33 of 100
building tree 34 of 100


[Parallel(n_jobs=-1)]: Done  33 tasks      | elapsed:   52.8s
[Parallel(n_jobs=-1)]: Done  34 tasks      | elapsed:   52.9s


building tree 35 of 100
building tree 36 of 100


[Parallel(n_jobs=-1)]: Done  35 tasks      | elapsed:   55.8s
[Parallel(n_jobs=-1)]: Done  36 tasks      | elapsed:   55.9s


building tree 37 of 100
building tree 38 of 100


[Parallel(n_jobs=-1)]: Done  37 tasks      | elapsed:   59.0s
[Parallel(n_jobs=-1)]: Done  38 tasks      | elapsed:   59.1s


building tree 39 of 100
building tree 40 of 100


[Parallel(n_jobs=-1)]: Done  39 tasks      | elapsed:  1.0min
[Parallel(n_jobs=-1)]: Done  40 tasks      | elapsed:  1.0min


building tree 41 of 100
building tree 42 of 100


[Parallel(n_jobs=-1)]: Done  41 tasks      | elapsed:  1.1min
[Parallel(n_jobs=-1)]: Done  42 tasks      | elapsed:  1.1min


building tree 43 of 100
building tree 44 of 100


[Parallel(n_jobs=-1)]: Done  43 tasks      | elapsed:  1.1min
[Parallel(n_jobs=-1)]: Done  44 tasks      | elapsed:  1.1min


building tree 45 of 100
building tree 46 of 100


[Parallel(n_jobs=-1)]: Done  45 tasks      | elapsed:  1.2min
[Parallel(n_jobs=-1)]: Done  46 tasks      | elapsed:  1.2min


building tree 47 of 100
building tree 48 of 100


[Parallel(n_jobs=-1)]: Done  47 tasks      | elapsed:  1.2min
[Parallel(n_jobs=-1)]: Done  48 tasks      | elapsed:  1.2min


building tree 49 of 100
building tree 50 of 100


[Parallel(n_jobs=-1)]: Done  49 tasks      | elapsed:  1.3min
[Parallel(n_jobs=-1)]: Done  50 tasks      | elapsed:  1.3min


building tree 51 of 100
building tree 52 of 100


[Parallel(n_jobs=-1)]: Done  51 tasks      | elapsed:  1.3min
[Parallel(n_jobs=-1)]: Done  52 tasks      | elapsed:  1.3min


building tree 53 of 100
building tree 54 of 100


[Parallel(n_jobs=-1)]: Done  53 tasks      | elapsed:  1.4min
[Parallel(n_jobs=-1)]: Done  54 tasks      | elapsed:  1.4min


building tree 55 of 100
building tree 56 of 100


[Parallel(n_jobs=-1)]: Done  55 tasks      | elapsed:  1.4min


building tree 57 of 100


[Parallel(n_jobs=-1)]: Done  56 tasks      | elapsed:  1.4min


building tree 58 of 100


[Parallel(n_jobs=-1)]: Done  57 tasks      | elapsed:  1.5min


building tree 59 of 100


[Parallel(n_jobs=-1)]: Done  58 tasks      | elapsed:  1.5min


building tree 60 of 100


[Parallel(n_jobs=-1)]: Done  59 tasks      | elapsed:  1.5min


building tree 61 of 100


[Parallel(n_jobs=-1)]: Done  60 tasks      | elapsed:  1.5min


building tree 62 of 100


[Parallel(n_jobs=-1)]: Done  61 tasks      | elapsed:  1.6min
[Parallel(n_jobs=-1)]: Done  62 tasks      | elapsed:  1.6min


building tree 63 of 100
building tree 64 of 100
building tree 65 of 100


[Parallel(n_jobs=-1)]: Done  63 tasks      | elapsed:  1.6min
[Parallel(n_jobs=-1)]: Done  64 tasks      | elapsed:  1.6min


building tree 66 of 100


[Parallel(n_jobs=-1)]: Done  65 tasks      | elapsed:  1.7min


building tree 67 of 100


[Parallel(n_jobs=-1)]: Done  66 tasks      | elapsed:  1.7min


building tree 68 of 100


[Parallel(n_jobs=-1)]: Done  67 tasks      | elapsed:  1.7min


building tree 69 of 100
building tree 70 of 100


[Parallel(n_jobs=-1)]: Done  68 tasks      | elapsed:  1.7min
[Parallel(n_jobs=-1)]: Done  69 tasks      | elapsed:  1.8min


building tree 71 of 100


[Parallel(n_jobs=-1)]: Done  70 tasks      | elapsed:  1.8min


building tree 72 of 100


[Parallel(n_jobs=-1)]: Done  71 tasks      | elapsed:  1.8min


building tree 73 of 100


[Parallel(n_jobs=-1)]: Done  72 tasks      | elapsed:  1.8min


building tree 74 of 100


[Parallel(n_jobs=-1)]: Done  73 tasks      | elapsed:  1.9min


building tree 75 of 100


[Parallel(n_jobs=-1)]: Done  74 tasks      | elapsed:  1.9min


building tree 76 of 100


[Parallel(n_jobs=-1)]: Done  75 tasks      | elapsed:  1.9min


building tree 77 of 100


[Parallel(n_jobs=-1)]: Done  76 tasks      | elapsed:  1.9min


building tree 78 of 100


[Parallel(n_jobs=-1)]: Done  77 tasks      | elapsed:  2.0min


building tree 79 of 100


[Parallel(n_jobs=-1)]: Done  78 tasks      | elapsed:  2.0min


building tree 80 of 100


[Parallel(n_jobs=-1)]: Done  79 tasks      | elapsed:  2.0min


building tree 81 of 100


[Parallel(n_jobs=-1)]: Done  80 tasks      | elapsed:  2.0min


building tree 82 of 100


[Parallel(n_jobs=-1)]: Done  81 tasks      | elapsed:  2.1min


building tree 83 of 100
building tree 84 of 100


[Parallel(n_jobs=-1)]: Done  82 tasks      | elapsed:  2.1min
[Parallel(n_jobs=-1)]: Done  83 tasks      | elapsed:  2.1min


building tree 85 of 100


[Parallel(n_jobs=-1)]: Done  84 tasks      | elapsed:  2.1min


building tree 86 of 100


[Parallel(n_jobs=-1)]: Done  85 tasks      | elapsed:  2.2min


building tree 87 of 100


[Parallel(n_jobs=-1)]: Done  86 tasks      | elapsed:  2.2min


building tree 88 of 100


[Parallel(n_jobs=-1)]: Done  87 tasks      | elapsed:  2.2min


building tree 89 of 100


[Parallel(n_jobs=-1)]: Done  88 tasks      | elapsed:  2.2min


building tree 90 of 100


[Parallel(n_jobs=-1)]: Done  89 tasks      | elapsed:  2.3min


building tree 91 of 100


[Parallel(n_jobs=-1)]: Done  90 tasks      | elapsed:  2.3min


building tree 92 of 100


[Parallel(n_jobs=-1)]: Done  91 tasks      | elapsed:  2.3min


building tree 93 of 100


[Parallel(n_jobs=-1)]: Done  92 tasks      | elapsed:  2.3min


building tree 94 of 100


[Parallel(n_jobs=-1)]: Done  93 tasks      | elapsed:  2.4min


building tree 95 of 100


[Parallel(n_jobs=-1)]: Done  94 tasks      | elapsed:  2.4min


building tree 96 of 100


[Parallel(n_jobs=-1)]: Done  95 tasks      | elapsed:  2.4min


building tree 97 of 100


[Parallel(n_jobs=-1)]: Done  96 tasks      | elapsed:  2.4min


building tree 98 of 100


[Parallel(n_jobs=-1)]: Done  97 tasks      | elapsed:  2.5min


building tree 99 of 100
building tree 100 of 100


[Parallel(n_jobs=-1)]: Done 100 out of 100 | elapsed:  2.5min finished
[Parallel(n_jobs=2)]: Using backend ThreadingBackend with 2 concurrent workers.
[Parallel(n_jobs=2)]: Done   1 tasks      | elapsed:    0.0s
[Parallel(n_jobs=2)]: Done   2 tasks      | elapsed:    0.0s
[Parallel(n_jobs=2)]: Done   3 tasks      | elapsed:    0.0s
[Parallel(n_jobs=2)]: Done   4 tasks      | elapsed:    0.0s
[Parallel(n_jobs=2)]: Done   5 tasks      | elapsed:    0.1s
[Parallel(n_jobs=2)]: Done   6 tasks      | elapsed:    0.1s
[Parallel(n_jobs=2)]: Done   7 tasks      | elapsed:    0.1s
[Parallel(n_jobs=2)]: Done   8 tasks      | elapsed:    0.1s
[Parallel(n_jobs=2)]: Done   9 tasks      | elapsed:    0.1s
[Parallel(n_jobs=2)]: Done  10 tasks      | elapsed:    0.1s
[Parallel(n_jobs=2)]: Done  11 tasks      | elapsed:    0.1s
[Parallel(n_jobs=2)]: Done  12 tasks      | elapsed:    0.1s
[Parallel(n_jobs=2)]: Done  13 tasks      | elapsed:    0.2s
[Parallel(n_jobs=2)]: Done  14 tasks      | elapsed:    

Accuracy of Random Forest classifier is: 0.590988 


In [ ]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
matrix = confusion_matrix(y_test,y_pred, labels=[1,-1])
print('Confusion matrix : \n',matrix)

# outcome values order in sklearn
tp, fn, fp, tn = confusion_matrix(y_test,y_pred,labels=[1,-1]).reshape(-1)
print('Outcome values : \n', tp, fn, fp, tn)

# classification report for precision, recall f1-score and accuracy
matrix = classification_report(y_test,y_pred,labels=[1,-1])
print('Classification report : \n',matrix)

Confusion matrix : 
 [[5660 1725]
 [4175 2865]]
Outcome values : 
 5660 1725 4175 2865
Classification report : 
               precision    recall  f1-score   support

           1       0.58      0.77      0.66      7385
          -1       0.62      0.41      0.49      7040

    accuracy                           0.59     14425
   macro avg       0.60      0.59      0.58     14425
weighted avg       0.60      0.59      0.58     14425



#SVM Classifier

*   Accuracy: 57.59%



In [ ]:
print("training SVM classifier now ...")
print("current time:-", datetime.datetime.now())
svm_classifier = svm.SVC(verbose=12).fit(X_train,y_train)
y_pred = svm_classifier.predict(X_test)
acc = accuracy_score(y_test,y_pred)
print('Accuracy of SVM classifier is: %f ' % acc)
print("current time:-", datetime.datetime.now())

training SVM classifier now ...
current time:- 2021-04-08 07:41:21.350902
[LibSVM]Accuracy of SVM classifier is: 0.575945 
current time:- 2021-04-08 09:19:44.593314


In [ ]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
matrix = confusion_matrix(y_test,y_pred, labels=[1,-1])
print('Confusion matrix : \n',matrix)

# outcome values order in sklearn
tp, fn, fp, tn = confusion_matrix(y_test,y_pred,labels=[1,-1]).reshape(-1)
print('Outcome values : \n', tp, fn, fp, tn)

# classification report for precision, recall f1-score and accuracy
matrix = classification_report(y_test,y_pred,labels=[1,-1])
print('Classification report : \n',matrix)

Confusion matrix : 
 [[5856 1529]
 [4588 2452]]
Outcome values : 
 5856 1529 4588 2452
Classification report : 
               precision    recall  f1-score   support

           1       0.56      0.79      0.66      7385
          -1       0.62      0.35      0.44      7040

    accuracy                           0.58     14425
   macro avg       0.59      0.57      0.55     14425
weighted avg       0.59      0.58      0.55     14425

